### PR TITLE
Update to the repo structure and usage of tests.

### PR DESCRIPTION
**Pull request by jake-g00dwin**
Sets up a more sane repo layout by using git sub-modules instead of work spaces for now. Also comes with example rust integration tests.

### CODE REVIEW

**Review by stackunderfl0w — CHANGES_REQUESTED** [review]
Why the change to compiling to x86? This change makes it so the repo doesn't compile for me. Did some other change alter the needed compile instructions? Also I cannot get the submodules to download correctly from either git clone recursive or submodule init.

**Comment by jake-g00dwin** [comment]
**X86 compilation**

I've changed the build target in the main repo back to the arm one, so we'll just have to manually pass if the target parameter for testing which I added info about in the README file.

**Sub-modules**
The git sub-module lets us partition the code into sub-modules that each can be their own device agnostic repo. This means we can do sensor driver development separately as well as track issues/bugs for those repos instead of having one super giant repo that's flooded with issues that may not be related to the actual micro-controller's code at all.

This also lets us make and test changes to the git sub-modules code on the fly; unlike cargo's crates system we can edit the source code for git sub-modules in place; where as there isn't a good way to read/edit source code for external crates that are marked as dependencies.

**Review by jake-g00dwin — COMMENTED** [review]
changes show older state of branch.

**Comment by stackunderfl0w** [comment]
Is there any particular reason you want to switch over to a structure with different modules being broken up into their own repos? I don't see any particular benefit, though I may be missing something. Each module interface should be simple enough to only need one or two files to implement, so having an entire repo for each seems to me to just be adding clutter.

**Comment by jake-g00dwin** [comment]
Going to cancel the PR, Instead going to include it like the other git dependencies

**Pull request closed without merging**
